#!/bin/bash

#set -x
set -Eeuo pipefail

update_repo() {
    local repo_name="$1"
    local repo_remote="$2"

    if [ -d "$repo_name" ]; then
        #git -C "$repo_name" pull
        git -C "$repo_name" fetch --all
    else
        mkdir "$repo_name"
        git -C "$repo_name" clone "$repo_remote" "$repo_name"
    fi
}

mkdir -p "$(dirname "${BASH_SOURCE[0]}")/repos"
cd "$(dirname "${BASH_SOURCE[0]}")/repos"

# TODO: add args
update_repo gentoo https://github.com/gentoo/gentoo.git
update_repo gentoo-zh https://github.com/microcai/gentoo-zh.git
